name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push
        run: |
          VERSION=$( cat VERSION )
          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          docker build . --tag $IMAGE:$VERSION --tag $IMAGE:latest
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest
